# Generated by Django 6.0.2 on 2026-08-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_lotes', models.IntegerField()),
                ('desglose_por_tipo', models.JSONField(default=dict)),
                ('codigo_certificado', models.CharField(blank=True, max_length=50, unique=True)),
                ('qr_certificado', models.CharField(blank=True, max_length=255)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='empresas.empresa')),
            ],
            options={
                'db_table': 'certificados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
