# Generated by Django 4.2 on 2026-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('certificados', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='lotes',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='numero_lotes',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='total_kg',
        ),
        migrations.AddField(
            model_name='certificado',
            name='numero_servicios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificado',
            name='servicios',
            field=models.ManyToManyField(related_name='certificados', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='total_escombros',
            field=models.IntegerField(default=0, help_text='Cantidad de retiros de escombros'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='total_reciclables_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='certificado',
            name='total_rsd_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
