# Generated by Django 6.0.2 on 2026-08-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_remove_certificado_lotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente / Válido'), ('anulado', 'Anulado / Revocado')], default='vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='certificado',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 PDF'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de Anulación'),
        ),
    ]
