# Generated by Django 6.0.2 on 2026-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('recolectado', 'Recolectado en terreno'), ('recibido', 'Recibido en bodega'), ('procesando', 'Iniciado procesamiento'), ('procesado', 'Procesamiento completado'), ('vendido', 'Vendido/Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos/eventos/%Y/%m/%d/')),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
