# Generated by Django 6.0.2 on 2026-08-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='lotes.lote'),
        ),
    ]
