# Generated by Django 6.0.2 on 2026-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT Empresa')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('rubro', models.CharField(choices=[('manufactura', 'Manufactura'), ('construccion', 'Construcción'), ('retail', 'Retail / Comercio'), ('alimentacion', 'Alimentación'), ('logistica', 'Logística / Transporte'), ('mineria', 'Minería'), ('servicios', 'Servicios'), ('educacion', 'Educación'), ('salud', 'Salud'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=80, verbose_name='Cargo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/empresas/')),
                ('activa', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
