# Generated by Django 6.0.2 on 2026-08-10 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ciudad_empresa_region_solicitudrecoleccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edp', models.CharField(max_length=50, unique=True, verbose_name='N° Estado de Pago')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('total_servicios', models.IntegerField(default=0)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal Neto ($)')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA 19% ($)')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Bruto ($)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador Interno'), ('emitido', 'Emitido'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edps_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_de_pago', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Estado de Pago Interno',
                'verbose_name_plural': 'Estados de Pago Internos',
                'db_table': 'estados_de_pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
