# Generated by Django 6.0.2 on 2026-08-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_estadodepago'),
        ('servicios', '0002_servicio_planta_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Giro Comercial'),
        ),
        migrations.CreateModel(
            name='DetalleEstadoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad_medida', models.CharField(default='servicio', max_length=30)),
                ('tarifa_unitaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empresas.estadodepago')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Estado de Pago',
                'verbose_name_plural': 'Detalles de Estado de Pago',
                'db_table': 'detalles_estado_de_pago',
            },
        ),
    ]
