# Generated by Django 6.0.2 on 2026-08-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_giro_detalleestadodepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('rsd', 'RSD'), ('escombros', 'RESCON / Escombros'), ('reciclables', 'Reciclables')], default='reciclables', max_length=30)),
                ('tipo_material', models.CharField(help_text='ej: pet, carton, vidrio, latas, rsd, escombros', max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Unitario ($)')),
                ('unidad_medida', models.CharField(default='kg', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tarifa Comercial Empresa',
                'verbose_name_plural': 'Tarifas Comerciales Empresa',
                'db_table': 'tarifas_empresa',
                'unique_together': {('empresa', 'modulo', 'tipo_material')},
            },
        ),
    ]
