# Generated by Django 6.0.2 on 2026-08-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_tarifaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='cantidad_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='modulo',
            field=models.CharField(choices=[('rsd', 'RSD / Basura'), ('escombros', 'Escombros / RESCON'), ('reciclables', 'Reciclables / Eco-equivalencia')], default='reciclables', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='tipo_material',
            field=models.CharField(choices=[('carton', 'Cartón / Papel'), ('pet', 'Botellas PET'), ('vidrio', 'Vidrio'), ('latas', 'Latas de Aluminio'), ('film', 'Film LDPE'), ('plastico', 'Plástico General'), ('escombros', 'Escombros / RESCON'), ('rsd', 'RSD / Basura General'), ('mixto', 'Mixto / Varios')], default='carton', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='solicitudrecoleccion',
            name='unidad_medida',
            field=models.CharField(default='kg', max_length=30),
        ),
        migrations.AlterField(
            model_name='estadodepago',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_de_pago', to='empresas.empresa', verbose_name='Empresa Solicitante'),
        ),
    ]
