# Generated by Django 4.2 on 2026-08-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_solicitudrecoleccion_cantidad_estimada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='Cargo / Área')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('recibe_certificados', models.BooleanField(default=False, verbose_name='Recibe Certificados de Trazabilidad')),
                ('recibe_estados_pago', models.BooleanField(default=False, verbose_name='Recibe Estados de Pago')),
                ('recibe_reportes', models.BooleanField(default=False, verbose_name='Recibe Reportes Operacionales')),
                ('recibe_notificaciones', models.BooleanField(default=True, verbose_name='Recibe Notificaciones Generales')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contacto de Empresa',
                'verbose_name_plural': 'Contactos de Empresa',
                'db_table': 'contactos_empresa',
                'ordering': ['nombre'],
            },
        ),
    ]
