# Generated by Django 4.2 on 2026-08-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_contacto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadodepago',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='solicitudrecoleccion',
            name='modulo',
            field=models.CharField(choices=[('rsd', 'RSD / Basura'), ('escombros', 'Escombros / RESCON'), ('reciclables', 'Reciclables / Eco-equivalencia'), ('otros', 'Otros / Servicio Personalizado')], default='reciclables', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudrecoleccion',
            name='tipo_material',
            field=models.CharField(choices=[('carton', 'Cartón / Papel'), ('pet', 'Botellas PET'), ('vidrio', 'Vidrio'), ('latas', 'Latas de Aluminio'), ('film', 'Film LDPE'), ('plastico', 'Plástico General'), ('escombros', 'Escombros / RESCON'), ('rsd', 'RSD / Basura General'), ('mixto', 'Mixto / Varios'), ('otros', 'Otro Material / Servicio Especial')], default='carton', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarifaempresa',
            name='modulo',
            field=models.CharField(choices=[('rsd', 'RSD / Basura'), ('escombros', 'RESCON / Escombros'), ('reciclables', 'Reciclables / Eco-equivalencia'), ('otros', 'Otros / Servicio Personalizado')], default='reciclables', max_length=30),
        ),
    ]
