# Generated by Django 4.2 on 2026-08-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_estadodepago_orden_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rubro_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otro rubro'),
        ),
    ]
