# Generated by Django 6.0.2 on 2026-08-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_rubro_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleestadodepago',
            name='fechas_texto',
            field=models.TextField(blank=True, help_text='Fechas agrupadas de los servicios realizados en formato dd/mm/aaaa', null=True),
        ),
    ]
