# Generated by Django 6.0.2 on 2026-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_detalleestadodepago_fechas_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodepago',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_de_pago', to='empresas.empresa', verbose_name='Empresa Solicitante'),
        ),
    ]
