# Generated by Django 6.0.2 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_estadodepago_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleestadodepago',
            options={'ordering': ['fecha_servicio', 'id'], 'verbose_name': 'Detalle de Estado de Pago', 'verbose_name_plural': 'Detalles de Estado de Pago'},
        ),
        migrations.AlterModelOptions(
            name='estadodepago',
            options={'ordering': ['-total_bruto', '-fecha_creacion'], 'verbose_name': 'Estado de Pago Interno', 'verbose_name_plural': 'Estados de Pago Internos'},
        ),
    ]
