# Generated by Django 6.0.2 on 2026-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_detalleestadodepago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodepago',
            name='estado',
            field=models.CharField(choices=[('emitido', 'Emitido'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='emitido', max_length=20),
        ),
    ]
