# Generated by Django 6.0.2 on 2026-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_estadodepago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='servicios_predeterminados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de casillas con servicios predeterminados que Redimir realiza a esta empresa.', verbose_name='Servicios Predeterminados'),
        ),
    ]
