# Generated by Django 4.2 on 2026-08-10 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_ciudad_empresa_region_solicitudrecoleccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('rsd', 'RSD / Basura'), ('escombros', 'Escombros / RESCON'), ('reciclables', 'Reciclables / Eco-equivalencia')], max_length=20)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('programado', 'Programado'), ('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('retirado', 'Retirado'), ('pendiente_validacion', 'Pendiente de Validación'), ('observado', 'Observado'), ('validado', 'Validado'), ('documento_emitido', 'Documento Emitido'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('ventana_inicio', models.TimeField(blank=True, null=True, verbose_name='Hour desde')),
                ('ventana_fin', models.TimeField(blank=True, null=True, verbose_name='Hora hasta')),
                ('fecha_retiro_real', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto_responsable', models.CharField(blank=True, max_length=150)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('cantidad_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_estimada', models.CharField(blank=True, default='kg', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observacion_admin', models.TextField(blank=True, verbose_name='Observación del administrador')),
                ('fecha_emision_doc', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='empresas.empresa')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_emisor_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('rsd', 'RSD / Basura Domiciliaria'), ('basura_general', 'Basura General'), ('rechazo', 'Rechazo / No-reciclable'), ('organico', 'Orgánico'), ('mixto', 'Mixto')], default='rsd', max_length=30)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_externo', models.CharField(max_length=100, verbose_name='N° Ticket Externo')),
                ('destino_receptor', models.CharField(choices=[('socsal', 'SOCSAL - Relleno Sanitario'), ('relleno_regional', 'Relleno Sanitario Regional'), ('municipalidad', 'Municipalidad'), ('otro', 'Otro Receptor Autorizado')], default='socsal', max_length=50)),
                ('destino_otro', models.CharField(blank=True, max_length=200, verbose_name='Especificar destino')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_rsd_set', to='servicios.servicio')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro RSD',
                'db_table': 'registros_rsd',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroReciclables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('carton', 'Cartón'), ('papel', 'Papel'), ('pet', 'Botellas PET (Plástico)'), ('latas', 'Latas de Aluminio'), ('film', 'Film LDPE'), ('carretes', 'Carretes'), ('sunchos', 'Sunchos'), ('vidrio', 'Vidrio'), ('tetrapak', 'Tetrapak'), ('plastico', 'Plástico general'), ('pallets', 'Pallets'), ('otro', 'Otro')], max_length=30)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades (carretes, sacos, pallets, etc.)')),
                ('destino', models.CharField(choices=[('interno', 'Gestión interna Redimir'), ('gestor', 'Gestor autorizado'), ('receptor', 'Receptor directo')], default='gestor', max_length=20)),
                ('destino_otro', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255)),
                ('eco_agua_L', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eco_co2_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eco_energia_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eco_petroleo_L', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eco_arboles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_reciclables_set', to='servicios.servicio')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Reciclable',
                'db_table': 'registros_reciclables',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEscombros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('escombros', 'Escombros'), ('rescon', 'RESCON'), ('aridos', 'Áridos'), ('tierra', 'Tierra'), ('voluminoso', 'Voluminoso'), ('mixto', 'Mixto')], default='escombros', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('m3', 'Metros Cúbicos (m³)'), ('sacos', 'Sacos'), ('batea', 'Batea'), ('camion', 'Camión'), ('otro', 'Otro')], default='m3', max_length=20)),
                ('ticket_externo', models.CharField(max_length=100, verbose_name='N° Ticket Externo')),
                ('destino_receptor', models.CharField(choices=[('municipalidad', 'Municipalidad'), ('rescon', 'RESCON Autorizado'), ('esavi', 'ESAVI'), ('otro', 'Otro Receptor Autorizado')], default='municipalidad', max_length=30)),
                ('destino_otro', models.CharField(blank=True, max_length=200)),
                ('cert_recepcion', models.FileField(blank=True, null=True, upload_to='certs_recepcion/%Y/%m/', verbose_name='Certificado de Recepción (opcional)')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_escombros_set', to='servicios.servicio')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Escombros',
                'db_table': 'registros_escombros',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FotoRegistroRSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='registros/rsd/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.registrorsd')),
            ],
            options={
                'db_table': 'fotos_rsd',
                'ordering': ['-es_principal', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='FotoRegistroReciclables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='registros/reciclables/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.registroreciclables')),
            ],
            options={
                'db_table': 'fotos_reciclables',
            },
        ),
        migrations.CreateModel(
            name='FotoRegistroEscombros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='registros/escombros/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.registroescombros')),
            ],
            options={
                'db_table': 'fotos_escombros',
            },
        ),
    ]
