# Generated by Django 6.0.2 on 2026-08-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='planta_destino',
            field=models.CharField(blank=True, max_length=200, verbose_name='Planta / Destino Receptor'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contacto_responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección de Retiro'),
        ),
    ]
