# Generated by Django 6.0.2 on 2026-09-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_estadodepago_estado'),
        ('servicios', '0002_servicio_planta_destino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaterialRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Material')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código / Abreviación')),
                ('categoria', models.CharField(choices=[('Reciclaje', 'Reciclaje (Papel, Cartón, Plástico, etc.)'), ('Madera', 'Madera y Derivados (Pallets, Carretes)'), ('Envases', 'Envases y Contenedores (Tambores, Bidones)'), ('Metales', 'Metales y Chatarra (Aluminio, Zuncho, etc.)'), ('Domestico', 'Residuos Domésticos / Basura'), ('Peligroso', 'Residuos Peligrosos (RESPEL)'), ('Otro', 'Otros Residuos')], default='Reciclaje', max_length=50, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Solo Kilogramos (kg)'), ('un', 'Solo Unidades (un)'), ('kg_un', 'Kilogramos y Unidades (kg + un)')], default='kg', max_length=20, verbose_name='Unidad de Medida')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo Material Retiro',
                'verbose_name_plural': 'Catálogo Materiales Retiro',
                'db_table': 'catalogos_material_retiro',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TicketRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, max_length=100, verbose_name='N° de Ticket / Folio')),
                ('fecha', models.DateField(verbose_name='Fecha de Retiro')),
                ('faena_area', models.CharField(blank=True, max_length=200, verbose_name='Instalación / Faena / Área')),
                ('tipo_servicio', models.CharField(blank=True, help_text='Ej: Áreas Productivas, Bodega APD, Puntos Verdes, Retiro Doméstico, Recepción de Ramplas', max_length=200, verbose_name='Tipo de Servicio / Área')),
                ('tipo_residuo', models.CharField(default='Reciclaje', help_text='Ej: Reciclaje, Residuos Domésticos, Chatarra', max_length=200, verbose_name='Tipo de Residuo General')),
                ('peso_total_ticket', models.DecimalField(decimal_places=2, help_text='Peso oficial de pesaje / báscula', max_digits=12, verbose_name='Peso Total Báscula (kg)')),
                ('respaldo_ticket', models.FileField(blank=True, null=True, upload_to='tickets_retiro/respaldos/%Y/%m/', verbose_name='Comprobante de Pesaje (Foto / PDF)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_retiro', to='empresas.empresa', verbose_name='Empresa / Cliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_pesaje', to='servicios.servicio', verbose_name='Servicio Asociado')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ticket de Retiro',
                'verbose_name_plural': 'Tickets de Retiro',
                'db_table': 'tickets_retiro',
                'ordering': ['-fecha', '-numero_ticket'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMaterialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso (kg)')),
                ('cantidad_unidades', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: unidades de pallets, tambores, carretes, etc.', max_digits=10, null=True, verbose_name='Cantidad (Unidades)')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones / Detalle')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='servicios.catalogomaterialretiro', verbose_name='Material')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.ticketretiro', verbose_name='Ticket de Retiro')),
            ],
            options={
                'verbose_name': 'Detalle de Material en Ticket',
                'verbose_name_plural': 'Detalles de Materiales en Tickets',
                'db_table': 'detalles_material_ticket',
                'ordering': ['material__orden', 'material__nombre'],
            },
        ),
    ]
