# Generated by Django 6.0.2 on 2026-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_catalogomaterialretiro_ticketretiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomaterialretiro',
            name='peso_unitario_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 20 kg por palet, 5.5 kg por carrete de madera, 10 kg por tambor, 1 kg por bidón 20L', max_digits=8, verbose_name='Factor conversión a kg (kg por unidad)'),
        ),
    ]
