# Generated by Django 6.0.2 on 2026-08-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(blank=True, max_length=50, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('tipo_residuo', models.CharField(choices=[('plastico', 'Plástico'), ('metal', 'Metal'), ('papel', 'Papel/Cartón'), ('vidrio', 'Vidrio'), ('organico', 'Orgánico'), ('mixto', 'Mixto')], max_length=20)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recoleccion', models.DateTimeField(auto_now_add=True)),
                ('foto_recoleccion', models.ImageField(upload_to='fotos/recolecciones/%Y/%m/%d/')),
                ('observaciones_recoleccion', models.TextField(blank=True)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('recolectado', 'Recolectado'), ('recibido', 'Recibido en Bodega'), ('procesando', 'En Procesamiento'), ('procesado', 'Procesado'), ('vendido', 'Vendido')], default='recolectado', max_length=20)),
                ('fecha_recepcion_bodega', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('peso_final_procesado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto_procesamiento', models.ImageField(blank=True, null=True, upload_to='fotos/procesamiento/%Y/%m/%d/')),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente_venta', models.CharField(blank=True, max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='empresas.empresa')),
            ],
            options={
                'db_table': 'lotes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
