# Generated by Django 6.0.2 on 2026-08-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/recolecciones/extra/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extra', to='lotes.lote')),
            ],
            options={
                'db_table': 'lotes_evidencias',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
