# Generated by Django 4.2 on 2026-08-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_evidencialote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='foto_camion',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/camion/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='lote',
            name='foto_ticket',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/tickets/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lote',
            name='foto_recoleccion',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/recolecciones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_residuo',
            field=models.CharField(choices=[('plastico', 'Plástico'), ('metal', 'Metal'), ('papel', 'Papel/Cartón'), ('vidrio', 'Vidrio'), ('organico', 'Orgánico'), ('basura', 'RSD / Basura General'), ('escombros', 'Escombros / RESCON'), ('mixto', 'Mixto / Varios')], default='mixto', max_length=50),
        ),
        migrations.CreateModel(
            name='DetalleLoteResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_residuos', to='lotes.lote')),
            ],
            options={
                'db_table': 'lotes_detalles_residuos',
            },
        ),
    ]
