# Generated by Django 6.0.2 on 2026-08-28 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_lote_foto_camion_lote_foto_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_recoleccion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Recolección/Retiro'),
        ),
    ]
