# Generated by Django 4.2 on 2026-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login_custom',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
