# Generated by Django 4.2 on 2026-08-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar_usuario_ultimo_login_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador Redimir'), ('recolector', 'Recolector / Operador'), ('empresa', 'Contacto de Empresa')], default='recolector', max_length=20),
        ),
    ]
