# Generated by Django 6.0.2 on 2026-08-10 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_role_recolector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('gerencia', 'Gerencia / Superadmin'), ('admin', 'Administrador Redimir'), ('recolector', 'Recolector / Operador'), ('empresa', 'Contacto de Empresa')], default='recolector', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Desactivación / Eliminación Lógica'), ('validacion', 'Validación de Servicio'), ('emision_doc', 'Emisión de Documento'), ('login', 'Inicio de Sesión'), ('configuracion', 'Cambio de Configuración')], max_length=30)),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo Afectado')),
                ('registro_id', models.CharField(blank=True, max_length=50, verbose_name='ID / Folio Registro')),
                ('detalles', models.TextField(verbose_name='Detalles / Cambios Realizados')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
