# Generated by Django 6.0.2 on 2026-08-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='campo_modificado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Campo Modificado'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='valor_anterior',
            field=models.TextField(blank=True, verbose_name='Valor Anterior'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='valor_nuevo',
            field=models.TextField(blank=True, verbose_name='Valor Nuevo'),
        ),
    ]
