# Generated by Django 6.0.2 on 2026-08-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_detalleestadodepago_fechas_texto'),
        ('usuarios', '0005_auditlog_campo_modificado_auditlog_valor_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='empresas.empresa'),
        ),
    ]
