# Generated by Django 4.2 on 2026-08-10 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorEcoEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('carton', 'Cartón'), ('papel', 'Papel'), ('pet', 'Plástico PET'), ('latas', 'Latas de Aluminio'), ('film', 'Film LDPE'), ('carretes', 'Carretes'), ('sunchos', 'Sunchos'), ('vidrio', 'Vidrio'), ('tetrapak', 'Tetrapak'), ('plastico', 'Plástico general'), ('pallets', 'Pallets'), ('otro', 'Otro')], max_length=30, verbose_name='Material')),
                ('factor_agua_lxkg', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Ahorro de Agua (L/kg)')),
                ('factor_co2_kgxkg', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Ahorro CO₂ (kg/kg)')),
                ('factor_energia_kwhxkg', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Ahorro de Energía (kWh/kg)')),
                ('factor_petroleo_lxkg', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Ahorro de Petróleo (L/kg)')),
                ('factor_arboles_kgxkg', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Árboles no talados (árbol/kg)')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Vigente desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas / fuente del factor')),
            ],
            options={
                'verbose_name': 'Factor Eco-Equivalencia',
                'verbose_name_plural': 'Factores Eco-Equivalencia',
                'db_table': 'factores_eco_equivalencia',
                'ordering': ['material', '-fecha_inicio'],
            },
        ),
    ]
