# Generated by Django 6.0.2 on 2026-08-11 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factorecoequivalencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factorecoequivalencia',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='factorecoequivalencia',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión del Factor'),
        ),
    ]
